core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('hr/', include('hr.urls')),
    path('product/', include('product.urls')),

]

hr/urls.py
from django.urls import path

from hr.views.customer import CustomerList
from hr.views.supplier import SupplierList

app_name = 'hr'

urlpatterns = [
    path('customers/', CustomerList.as_view(), name='customer_list'),
    path('supplier/', SupplierList.as_view(), name='supplier_list'),
    ]

product/urls.py
from django.urls import path

from product.views.sale.sales import SalesList
from product.views.expense.manage_expense import ManageExpense

app_name = 'product'

urlpatterns = [
    path('', SalesList.as_view(), name='sales_list'),
    path('expense/', ManageExpense.as_view(), name='manage_expense'),

    ]

abstract/utils/models.py
from django.db import models
from django.utils.timezone import now
import uuid


class Timestamp(models.Model):
    """ Abstract base model for create and update timestamp and user for all models. """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(default=now, editable=False)
    updated_at = models.DateTimeField(default=now, editable=False)

    class Meta:
        abstract = True

'''
In Bangladesh, we have offices in all eight administrative divisions. These divisions are divided into 64 districts.
'''
DISTRICTS = (
    ('dhaka', 'Dhaka'),
    ('faridpur', 'Faridpur'),
    ('gazipur', 'Gazipur'),
    ('gopalganj', 'Gopalganj'),
    ('jamalpur', 'Jamalpur'),
    ('kishoreganj', 'Kishoreganj'),
    ('madaripur', 'Madaripur'),
    ('manikganj', 'Manikganj'),
    ('munshiganj', 'Munshiganj'),
    ('narayanganj', 'Narayanganj'),
    ('narsingdi', 'Narsingdi'),
    ('netrokona', 'Netrokona'),
    ('rajbari', 'Rajbari'),
    ('shariatpur', 'Shariatpur'),
    ('sherpur', 'Sherpur'),
    ('tangail', 'Tangail'),
    ('bogra', 'Bogra'),
    ('joypurhat', 'Joypurhat'),
    ('naogaon', 'Naogaon'),
    ('natore', 'Natore'),
    ('nawabganj', 'Nawabganj'),
    ('pabna', 'Pabna'),
    ('rajshahi', 'Rajshahi'),
    ('sirajganj', 'Sirajganj'),
    ('dinajpur', 'Dinajpur'),
    ('gaibandha', 'Gaibandha'),
    ('kurigram', 'Kurigram'),
    ('lalmonirhat', 'Lalmonirhat'),
    ('nilphamari', 'Nilphamari'),
    ('panchagarh', 'Panchagarh'),
    ('rangpur', 'Rangpur'),
    ('thakurgaon', 'Thakurgaon'),
    ('barguna', 'Barguna'),
    ('barisal', 'Barisal'),
    ('bhola', 'Bhola'),
    ('jhalokati', 'Jhalokati'),
    ('patuakhali', 'Patuakhali'),
    ('pirojpur', 'Pirojpur'),
    ('bandarban', 'Bandarban'),
    ('brahmanbaria', 'Brahmanbaria'),
    ('chandpur', 'Chandpur'),
    ('chittagong', 'Chittagong'),
    ('comilla', 'Comilla'),
    ('cox\'s bazar', 'Cox\'s bazar'),
    ('feni', 'Feni'),
    ('khagrachhari', 'Khagrachhari'),
    ('lakshmipur', 'Lakshmipur'),
    ('noakhali', 'Noakhali'),
    ('rangamati', 'Rangamati'),
    ('habiganj', 'Habiganj'),
    ('moulvibazar', 'Moulvibazar'),
    ('sunamganj', 'Sunamganj'),
    ('sylhet', 'Sylhet'),
    ('bagerhat', 'Bagerhat'),
    ('chuadanga', 'Chuadanga'),
    ('jessore', 'Jessore'),
    ('jhenaidah', 'Jhenaidah'),
    ('khulna', 'Khulna'),
    ('kushtia', 'Kushtia'),
    ('magura', 'Magura'),
    ('meherpur', 'Meherpur'),
    ('narail', 'Narail'),
    ('satkhira', 'Satkhira'),
)


'''
The administrative structure of Bangladesh currently comprises eight divisions.

Barishal, Chattogram, Dhaka, Khulna, Rajshahi, Rangpur, Mymensingh and Sylhet.
'''
DIVISIONS = (
    ('dhaka', 'Dhaka'),
    ('sylhet', 'Sylhet'),
    ('barishal', 'Barishal'),
    ('chattogram', 'Chattogram'),
    ('khulna', 'Khulna'),
    ('rajshahi', 'Rajshahi'),
    ('rangpur', 'Rangpur'),
    ('mymensingh', 'Mymensingh'),
)


ACCOUNT_STATUS_CHOICE = (("open", "Open"), ("close", "Close"))

ACCOUNT_TYPE = (
    ('savings account', 'Savings Account'),
    ('current account', 'Current Account'),
    ('fixed Deposit account', 'Fixed Deposit Account'),
    ('recurring Deposit account', 'Recurring Deposit Account'),
)

INDUSTRYCHOICES = (
    ("ADVERTISING", "ADVERTISING"),
    ("AGRICULTURE", "AGRICULTURE"),
    ("APPAREL & ACCESSORIES", "APPAREL & ACCESSORIES"),
    ("AUTOMOTIVE", "AUTOMOTIVE"),
    ("BANKING", "BANKING"),
    ("BIOTECHNOLOGY", "BIOTECHNOLOGY"),
    ("BUILDING MATERIALS & EQUIPMENT", "BUILDING MATERIALS & EQUIPMENT"),
    ("CHEMICAL", "CHEMICAL"),
    ("COMPUTER", "COMPUTER"),
    ("EDUCATION", "EDUCATION"),
    ("ELECTRONICS", "ELECTRONICS"),
    ("ENERGY", "ENERGY"),
    ("ENTERTAINMENT & LEISURE", "ENTERTAINMENT & LEISURE"),
    ("FINANCE", "FINANCE"),
    ("FOOD & BEVERAGE", "FOOD & BEVERAGE"),
    ("GROCERY", "GROCERY"),
    ("HEALTHCARE", "HEALTHCARE"),
    ("INSURANCE", "INSURANCE"),
    ("LEGAL", "LEGAL"),
    ("MANUFACTURING", "MANUFACTURING"),
    ("PUBLISHING", "PUBLISHING"),
    ("REAL ESTATE", "REAL ESTATE"),
    ("SERVICE", "SERVICE"),
    ("SOFTWARE", "SOFTWARE"),
    ("SPORTS", "SPORTS"),
    ("TECHNOLOGY", "TECHNOLOGY"),
    ("TELECOMMUNICATIONS", "TELECOMMUNICATIONS"),
    ("TELEVISION", "TELEVISION"),
    ("TRANSPORTATION", "TRANSPORTATION"),
    ("VENTURE CAPITAL", "VENTURE CAPITAL"),
)


def get_client_ip(request):
    x_forwarded_for = request.META.get("HTTP_X_FORWARDED_FOR")
    if x_forwarded_for:
        ip = x_forwarded_for.split(",")[0]
    else:
        ip = request.META.get("REMOTE_ADDR")
    return ip

abstract/templates/abstract/components/TodayExpenseCard.html
{% load today_expense %}
<div class="col-xl-3 col-md-6 mb-4">
  <div class="card border-left-danger shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">
            TODAY EXPENSE
          </div>
          <div class="h5 mb-0 font-weight-bold text-gray-800">{% get_today_expsense %} <small class="text-black">BDT</small></div>
        </div>
        <div class="col-auto">
          <i class="fas fa-file-invoice"></i>
        </div>
      </div>
    </div>
  </div>
</div>

abstract/templates/abstract/components/TotalCustomerCard.html
{% load customer_tags %}
<div class="col-xl-3 col-md-6 mb-4">
  <div class="card border-left-primary shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <div
            class="text-xs font-weight-bold text-primary text-uppercase mb-1"
          >
            <a class="hover:no-underline" href="{% url 'hr:customer_list' %}">Total Customer</a>
          </div>
          <div class="h5 mb-0 font-weight-bold text-gray-800">
            {% total_customer %}
          </div>
        </div>
        <div class="col-auto">
          <i class="fas fa-user"></i>
        </div>
      </div>
    </div>
  </div>
</div>

abstract/templates/abstract/components/TotalExpenseCard.html
{% load total_expense %}
<div class="col-xl-3 col-md-6 mb-4">
  <div class="card border-left-danger shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <div class="text-xs font-weight-bold text-uppercase mb-1">
            <a class="text-danger hover:no-underline" href="{% url 'product:manage_expense' %}">TOTAL EXPENSE</a>
          </div>
          <div class="h5 mb-0 font-weight-bold text-gray-800">
            {% get_total_expsense %} <small class="text-black">BDT</small>
          </div>
        </div>
        <div class="col-auto">
          <i class="fas fa-file-invoice"></i>
        </div>
      </div>
    </div>
  </div>
</div>

abstract/templates/abstract/components/TotalPurchaseCostCard.html
{% load total_purchase %}
<div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-primary shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-uppercase mb-1">
                        <a class="text-primary hover:no-underline" href="{% url 'product:manage_expense' %}">TOTAL PURCHASE COST</a>
                    </div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800">{% get_total_purchase %} <small class="text-black">BDT</small></div>
                </div>
                <div class="col-auto">
                    <i class="far fa-money-bill-alt"></i>
                </div>
            </div>
        </div>
    </div>
</div>

abstract/templates/abstract/components/TotalSaleCard.html
{% load total_sale %}
<div class="col-xl-3 col-md-6 mb-4">
<div class="card border-left-primary shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <div
            class="text-xs font-weight-bold text-primary text-uppercase mb-1"
          >
            <a class="hover:no-underline" href="{% url 'product:sales_list' %}">Total Sale</a>
          </div>
          <div class="h5 mb-0 font-weight-bold text-gray-800">{% get_total_sale %}</div>
        </div>
        <div class="col-auto">
          <i class="fas fa-wallet"></i>
        </div>
      </div>
    </div>
  </div>
</div>

abstract/templates/abstract/components/TotalSalesCard.html
{% load total_sale_balance %}
<div class="col-xl-3 col-md-6 mb-4">
  <div class="card border-left-primary shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <div
            class="text-xs font-weight-bold text-primary text-uppercase mb-1"
          >
            TOTAL SALE
          </div>
          <div class="h5 mb-0 font-weight-bold text-gray-800">{% total_balance %} <small class="text-black">BDT</small></div>
        </div>
        <div class="col-auto">
          <i class="fas fa-wallet"></i>
        </div>
      </div>
    </div>
  </div>
</div>

abstract/templates/abstract/components/TotalSupplierCard.html
{% load total_supplier %}
<div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-warning shadow h-100 py-2">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-purple text-uppercase mb-1">
                        <a class="hover:no-underline" href="{% url 'hr:supplier_list' %}">Total Supplier</a>
                    </div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800">{% get_total_supplier %}</div>
                </div>
                <div class="col-auto">
                    <i class="fas fa-people-carry fa-2x text-gray-300"></i>
                </div>
            </div>
        </div>
    </div>
</div>